PLUGINS_IMPORT_CONFIG = ["src.core.ls",
                         "src.core.cd",
                         "src.core.cat",
                         "src.core.rm",
                         "src.core.cp",
                         "src.core.mv",
                         "src.plugins.zip",
                         "src.plugins.unzip",
                         "src.plugins.tar",
                         "src.plugins.untar",
                         ]
